# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodebaseAnalyzer < Formula
  desc ""
  homepage "https://github.com/flagship-io/codebase-analyzer"
  version "0.5.2"

  on_macos do
    url "https://github.com/flagship-io/codebase-analyzer/releases/download/v0.5.2/codebase-analyzer_0.5.2_darwin_all.tar.gz"
    sha256 "5a23b3d144543043afe2c8008089a791706f5030d8b28465ce32dd9798607f6b"

    def install
      bin.install "codebase-analyzer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagship-io/codebase-analyzer/releases/download/v0.5.2/codebase-analyzer_0.5.2_linux_arm64.tar.gz"
      sha256 "9dacc8fbb8b7a27e5686d62832e0691e5cd6749299e5ff92ddff43e58b4b41f5"

      def install
        bin.install "codebase-analyzer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flagship-io/codebase-analyzer/releases/download/v0.5.2/codebase-analyzer_0.5.2_linux_amd64.tar.gz"
      sha256 "e786dd9ac18a234004049e06ccf6d66ad24fc65dd3a46b7f9fd2a39a2a3dcdcd"

      def install
        bin.install "codebase-analyzer"
      end
    end
  end
end
