# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodebaseAnalyzer < Formula
  desc ""
  homepage "https://github.com/flagship-io/codebase-analyzer"
  version "0.5.3"

  on_macos do
    url "https://github.com/flagship-io/codebase-analyzer/releases/download/v0.5.3/codebase-analyzer_0.5.3_darwin_all.tar.gz"
    sha256 "30701a5f3d6480236beb9b02c17fdfdbbe0d68332b137945f312057672f77f2d"

    def install
      bin.install "codebase-analyzer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagship-io/codebase-analyzer/releases/download/v0.5.3/codebase-analyzer_0.5.3_linux_arm64.tar.gz"
      sha256 "9578cae3f7b73304b8072420a96e6be930b46e89c3e256d35dc9dbeb1a901904"

      def install
        bin.install "codebase-analyzer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/flagship-io/codebase-analyzer/releases/download/v0.5.3/codebase-analyzer_0.5.3_linux_amd64.tar.gz"
      sha256 "33f5122c66e73ca007f41524a2f959768958a6ebb5d19d17aa6b277396ad6dd1"

      def install
        bin.install "codebase-analyzer"
      end
    end
  end
end
