# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flagship < Formula
  desc ""
  homepage "https://github.com/flagship-io/flagship"
  version "0.5.0"

  on_macos do
    url "https://github.com/flagship-io/flagship/releases/download/v0.5.0/flagship_0.5.0_darwin_all.tar.gz"
    sha256 "aac37ab541762d757ce925c284db2def0d08bb2e61c05afc2785e5da168a3820"

    def install
      bin.install "flagship"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flagship-io/flagship/releases/download/v0.5.0/flagship_0.5.0_linux_amd64.tar.gz"
      sha256 "6fb1096b1647a3c4791a9dcbc963f3aff41992788be7f16de20a95e01c0454f0"

      def install
        bin.install "flagship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagship-io/flagship/releases/download/v0.5.0/flagship_0.5.0_linux_arm64.tar.gz"
      sha256 "5a2617cb9b2c25dae6043a8d4d124ec491def5624ae79c937a441d4998a423ca"

      def install
        bin.install "flagship"
      end
    end
  end
end
