# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flagship < Formula
  desc ""
  homepage "https://github.com/flagship-io/flagship"
  version "0.7.1"

  on_macos do
    url "https://github.com/flagship-io/flagship/releases/download/v0.7.1/flagship_0.7.1_darwin_all.tar.gz"
    sha256 "7502dceb05fc396a70cdb4e5542aa5fb05dd68248369b779038a981a8aededb2"

    def install
      bin.install "flagship"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flagship-io/flagship/releases/download/v0.7.1/flagship_0.7.1_linux_amd64.tar.gz"
      sha256 "7799da93b7bdf9073800bc22e53843ad4f6431494d362a5c883dc115226699ad"

      def install
        bin.install "flagship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagship-io/flagship/releases/download/v0.7.1/flagship_0.7.1_linux_arm64.tar.gz"
      sha256 "0e87bf21ea6ea6157258d5ca5a60a6c71fceafcf0111ab2cda995b31dc435602"

      def install
        bin.install "flagship"
      end
    end
  end
end
