# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flagship < Formula
  desc ""
  homepage "https://github.com/flagship-io/flagship"
  version "0.7.3"

  on_macos do
    url "https://github.com/flagship-io/flagship/releases/download/v0.7.3/flagship_0.7.3_darwin_all.tar.gz"
    sha256 "f3b81b774c09cf36f743861592cc5992d70071476fd5e05b9cf1e4b116c1cf89"

    def install
      bin.install "flagship"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flagship-io/flagship/releases/download/v0.7.3/flagship_0.7.3_linux_amd64.tar.gz"
      sha256 "74b89134cba9cd7a70e24896b280527b5bc69d5f7532fb4626629729da0e316f"

      def install
        bin.install "flagship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flagship-io/flagship/releases/download/v0.7.3/flagship_0.7.3_linux_arm64.tar.gz"
      sha256 "2e6dbfddb4e4eea9f7ceeb36ea62087b9193661cec041383006ea2409aeebf44"

      def install
        bin.install "flagship"
      end
    end
  end
end
